### ISSUE TITLE
Text focus causes whole modal to go off screen

### ISSUE THREAD

**Issue by wilkinsonj** [birdwingo/react-native-swipe-modal#18]
When focusing in a text box within the modal, the top part of the modal disappears off screen, as does the focused text box

**Comment by Lipo11** [comment]
hello, can you provide video?

**Comment by jaikantshikray** [comment]
facing same issue when keyboard launched it goes out of view

**Comment by Awethentique** [comment]
I am experiencing the same issue when you have a text input field inside the modal.
![image](https://github.com/birdwingo/react-native-swipe-modal/assets/1106670/f30f1044-2e35-4d80-8872-be44eb660970)
If you tap into the input field to type something, the keyboard comes up and shifts the entire view up, thus shifting the input field off the top of the screen. you can try to scroll down it will dismiss the modal. I had to use `closeTrigger={isSearchFocused ? 'minHeight' : 'swipeDown'}` prop to try to make it so that the modal does not dismiss when the keyboard is focused. perhaps i could do better using this library to control the keyboard.

Using the closeTrigger hack, I get the modal not to dismiss when you try to scroll back to the input field, however the view just bounces back with the input field hidden again

![image](https://github.com/birdwingo/react-native-swipe-modal/assets/1106670/d6d47744-8e21-447f-b51c-85260b3d572b)

**Comment by Lipo11** [comment]
just use useKeyboardAvoidingView to false
